use std::collections::BTreeMap;

use serde::Serialize;

use super::manifest;
use super::manifest::Component;

#[derive(Serialize)]
#[serde(rename = "http_archive")]
struct HttpArchive {
    name: String,
    urls: Vec<String>,
    sha256: String,
    strip_prefix: String,
    #[serde(rename = "type")]
    kind: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "select")]
struct Select<T>(BTreeMap<String, T>);

#[derive(Serialize)]
#[serde(rename = "downloaded_node_toolchain")]
struct DownloadedNodeToolchain {
    name: String,
    archive: Select<String>,
    visibility: Vec<String>,
}

fn http_archive_for(comp: &Component) -> String {
    serde_starlark::to_string(&HttpArchive {
        name: comp.target_name.clone(),
        urls: vec![comp.url.clone()],
        sha256: comp.sha256.clone(),
        strip_prefix: comp.strip_prefix.clone(),
        kind: comp.kind.to_string(),
        visibility: vec![],
    })
    .expect("HttpArchive always serializes")
}

/// Target label for the canonical `config_setting` in
/// platforms/configs/BUCK matching a (cpu, os) pair.
fn platform_target(cpu: &str, os_name: &str) -> String {
    format!(
        "buckshot//platforms/configs:{}",
        manifest::platform_label(cpu, os_name)
    )
}

pub struct RenderInput<'a> {
    pub version: &'a str,
    pub host_triples: &'a [String],
    pub components: &'a [Component],
}

pub fn render(input: RenderInput) -> anyhow::Result<String> {
    let RenderInput {
        version,
        host_triples,
        components,
    } = input;

    if host_triples.is_empty() {
        anyhow::bail!("at least one host triple is required");
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `node toolchain` command -- do not edit by hand.\n# Release: https://nodejs.org/dist/{version}/\n\n"
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"http_archive\")\n");
    out.push_str("load(\":node_toolchain.bzl\", \"downloaded_node_toolchain\")\n\n");

    let mut parts: Vec<String> = Vec::new();

    for comp in components {
        parts.push(http_archive_for(comp));
    }

    // `archive` is keyed on the *execution* platform (see
    // `node_toolchain.bzl`'s `archive` doc) -- same `attrs.exec_dep` + flat
    // `select()` shape `rust/toolchain`'s `host_bundle` uses.
    let mut archive_map = BTreeMap::new();
    for (triple, comp) in host_triples.iter().zip(components) {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        let label = platform_target(cpu, os_name);
        archive_map.insert(label.clone(), format!(":{}", comp.target_name));
    }

    parts.push(
        serde_starlark::to_string(&DownloadedNodeToolchain {
            name: "toolchain".to_string(),
            archive: Select(archive_map),
            visibility: vec!["PUBLIC".to_string()],
        })
        .expect("DownloadedNodeToolchain always serializes"),
    );

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}
