use std::collections::BTreeMap;

use anyhow::Context;
use serde::Serialize;

use super::manifest;
use super::manifest::Component;

#[derive(Serialize)]
#[serde(rename = "http_archive")]
struct HttpArchive {
    name: String,
    urls: Vec<String>,
    sha256: String,
    size_bytes: u64,
    strip_prefix: String,
    #[serde(rename = "type")]
    kind: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "select")]
struct Select<T>(BTreeMap<String, T>);

#[derive(Serialize)]
#[serde(rename = "downloaded_node_toolchain")]
struct DownloadedNodeToolchain {
    name: String,
    archive: Select<String>,
    visibility: Vec<String>,
}

fn http_archive_for(comp: &Component) -> String {
    serde_starlark::to_string(&HttpArchive {
        name: comp.target_name.clone(),
        urls: vec![comp.url.clone()],
        sha256: comp.sha256.clone(),
        size_bytes: comp.size_bytes.expect("fetch_sizes runs before rendering"),
        strip_prefix: comp.strip_prefix.clone(),
        kind: comp.kind.to_string(),
        visibility: vec![],
    })
    .expect("HttpArchive always serializes")
}

/// Target label for the canonical `config_setting` in
/// platforms/configs/BUCK matching a (cpu, os) pair.
fn platform_target(cpu: &str, os_name: &str) -> String {
    format!(
        "buckshot//platforms/configs:{}",
        manifest::platform_label(cpu, os_name)
    )
}

pub struct RenderInput<'a> {
    pub version: &'a str,
    pub host_triples: &'a [String],
    pub components: &'a [Component],
}

pub fn render(input: RenderInput) -> anyhow::Result<String> {
    let RenderInput {
        version,
        host_triples,
        components,
    } = input;

    if host_triples.is_empty() {
        anyhow::bail!("at least one host triple is required");
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `node toolchain` command -- do not edit by hand.\n# Release: https://nodejs.org/dist/{version}/\n\n"
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"http_archive\")\n");
    out.push_str("load(\"@buckshot//node/toolchain:node_toolchain.bzl\", \"downloaded_node_toolchain\")\n\n");

    let mut parts: Vec<String> = Vec::new();

    for comp in components {
        parts.push(http_archive_for(comp));
    }

    // `archive` is keyed on the *execution* platform (see
    // `node_toolchain.bzl`'s `archive` doc) -- same `attrs.exec_dep` + flat
    // `select()` shape `rust/toolchain`'s `host_bundle` uses.
    let mut archive_map = BTreeMap::new();
    for (triple, comp) in host_triples.iter().zip(components) {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        let label = platform_target(cpu, os_name);
        archive_map.insert(label.clone(), format!(":{}", comp.target_name));
    }

    parts.push(
        serde_starlark::to_string(&DownloadedNodeToolchain {
            name: "toolchain".to_string(),
            archive: Select(archive_map),
            visibility: vec!["PUBLIC".to_string()],
        })
        .expect("DownloadedNodeToolchain always serializes"),
    );

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

// ==========================================================================
// Rolling aliases (`node/toolchains/BUCK`)
// ==========================================================================

#[derive(Serialize)]
#[serde(rename = "toolchain_alias")]
struct ToolchainAlias {
    name: String,
    actual: String,
    visibility: Vec<String>,
}

/// `(major, minor, patch)` version key for a `vX.Y.Z` release identifier.
fn version_key(name: &str) -> Option<(u64, u64, u64)> {
    crate::releases::semver_key(name.strip_prefix('v')?)
}

/// Renders the rolling-alias BUCK file for the given releases: one
/// `v<major>` alias per major line, each pointing at the latest release on
/// that line. Deterministic: same release set, same bytes.
pub fn render_aliases(releases: &[String]) -> String {
    let mut by_major: BTreeMap<u64, Vec<&String>> = BTreeMap::new();
    for release in releases {
        if let Some((major, _, _)) = version_key(release) {
            by_major.entry(major).or_default().push(release);
        }
    }
    for patches in by_major.values_mut() {
        patches.sort_by_key(|v| version_key(v));
    }

    let mut sorted: Vec<&String> = releases.iter().collect();
    sorted.sort_by_key(|v| version_key(v));

    let mut out = String::new();
    out.push_str("# @generated by buckshot's `node toolchain` command -- do not edit by hand.\n");
    out.push_str(&format!(
        "# Releases: {}\n\n",
        sorted
            .iter()
            .map(|v| v.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"toolchain_alias\")\n\n");

    let mut parts: Vec<String> = Vec::new();
    for (major, patches) in &by_major {
        let latest = patches.last().expect("non-empty patch list");
        parts.push(
            serde_starlark::to_string(&ToolchainAlias {
                name: format!("v{major}"),
                actual: format!("buckshot//node/toolchains/{latest}:toolchain"),
                visibility: vec!["PUBLIC".to_string()],
            })
            .expect("ToolchainAlias always serializes"),
        );
    }

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Re-renders `dir/BUCK` (the rolling `v<major>` aliases) from the versioned
/// releases on disk. Leaves the file untouched when no releases exist (e.g.
/// generating to a scratch `--output` outside the repo tree).
pub fn refresh_aliases(dir: &std::path::Path) -> anyhow::Result<()> {
    let releases = crate::releases::scan_releases(dir)?;
    for release in &releases {
        if version_key(release).is_none() {
            anyhow::bail!("{}/{release} is not a vX.Y.Z release", dir.display());
        }
    }
    if releases.is_empty() {
        eprintln!(
            "node toolchain: no releases under {}, leaving {}/BUCK unchanged",
            dir.display(),
            dir.display()
        );
        return Ok(());
    }
    let rendered = render_aliases(&releases);
    std::fs::write(dir.join("BUCK"), rendered)
        .with_context(|| format!("writing {}/BUCK", dir.display()))?;
    eprintln!(
        "node toolchain: refreshed {}/BUCK ({})",
        dir.display(),
        releases.join(", "),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn major_aliases_track_latest_release() {
        let out = render_aliases(&[
            "v24.11.0".to_string(),
            "v26.4.0".to_string(),
            "v26.5.0".to_string(),
        ]);
        assert!(out.contains("name = \"v24\""));
        assert!(out.contains("buckshot//node/toolchains/v24.11.0:toolchain"));
        assert!(out.contains("name = \"v26\""));
        assert!(out.contains("buckshot//node/toolchains/v26.5.0:toolchain"));
        assert!(!out.contains("v26.4.0:toolchain"));
        assert!(out.ends_with('\n'));
    }
}
