use std::collections::BTreeMap;

use anyhow::Context;
use serde::Serialize;

use super::manifest;
use super::manifest::Component;

#[derive(Serialize)]
#[serde(rename = "http_archive")]
struct HttpArchive {
    name: String,
    urls: Vec<String>,
    sha256: String,
    size_bytes: u64,
    strip_prefix: String,
    #[serde(rename = "type")]
    kind: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "select")]
struct Select<T>(BTreeMap<String, T>);

#[derive(Serialize)]
#[serde(rename = "node_host_bundle")]
struct NodeHostBundle {
    name: String,
    archive: Select<String>,
    path_style: Select<String>,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "downloaded_node_toolchain")]
struct DownloadedNodeToolchain {
    name: String,
    host: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    typescript: Option<String>,
    visibility: Vec<String>,
}

fn http_archive_for(comp: &Component) -> String {
    serde_starlark::to_string(&HttpArchive {
        name: comp.target_name.clone(),
        urls: vec![comp.url.clone()],
        sha256: comp.sha256.clone(),
        size_bytes: comp.size_bytes.expect("fetch_sizes runs before rendering"),
        strip_prefix: comp.strip_prefix.clone(),
        kind: comp.kind.to_string(),
        visibility: vec![],
    })
    .expect("HttpArchive always serializes")
}

/// Target label for the canonical `config_setting` in
/// platforms/configs/BUCK matching a (cpu, os) pair.
fn platform_target(cpu: &str, os_name: &str) -> String {
    format!(
        "buckshot//platforms/configs:{}",
        manifest::platform_label(cpu, os_name)
    )
}

pub struct RenderInput<'a> {
    pub version: &'a str,
    pub host_triples: &'a [String],
    pub components: &'a [Component],
    /// TypeScript major line (e.g. `"7"`) for the toolchain's `tsc`, or
    /// `None` for a tsc-less toolchain.
    pub typescript_version: Option<&'a str>,
}

/// Shared host-bundle rendering: flat `select()`s over the host triples'
/// config labels, resolved in the *execution* platform via
/// `attrs.exec_dep` (see `render`).
fn host_bundle_maps(
    host_triples: &[String],
    components: &[Component],
) -> anyhow::Result<(BTreeMap<String, String>, BTreeMap<String, String>)> {
    let mut archive_map = BTreeMap::new();
    let mut path_style_map = BTreeMap::new();
    for (triple, comp) in host_triples.iter().zip(components) {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        let label = platform_target(cpu, os_name);
        archive_map.insert(label.clone(), format!(":{}", comp.target_name));
        let path_style = match os_name {
            "windows" => "windows",
            _ => "unix",
        };
        path_style_map.insert(label, path_style.to_string());
    }
    Ok((archive_map, path_style_map))
}

pub fn render(input: RenderInput) -> anyhow::Result<String> {
    let RenderInput {
        version,
        host_triples,
        components,
        typescript_version,
    } = input;

    if host_triples.is_empty() {
        anyhow::bail!("at least one host triple is required");
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `node toolchain` command -- do not edit by hand.\n# Release: https://nodejs.org/dist/{version}/\n\n"
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"http_archive\")\n");
    out.push_str(
        "load(\"@buckshot//node/toolchain:node_toolchain.bzl\", \"downloaded_node_toolchain\", \"node_host_bundle\")\n\n",
    );

    let mut parts: Vec<String> = Vec::new();

    for comp in components {
        parts.push(http_archive_for(comp));
    }

    // Host-keyed selects, resolved in the *execution* platform: the
    // toolchain pulls the bundle in via `attrs.exec_dep`, so these fire
    // against the build host even when the toolchain itself is analyzed
    // in an exotic target configuration (e.g. OS-less wasm32) -- the same
    // `host_bundle` pattern `rust/toolchain` and `cxx/toolchain` use.
    let (archive_map, path_style_map) = host_bundle_maps(host_triples, components)?;

    parts.push(
        serde_starlark::to_string(&NodeHostBundle {
            name: "host".to_string(),
            archive: Select(archive_map),
            path_style: Select(path_style_map),
            visibility: vec![],
        })
        .expect("NodeHostBundle always serializes"),
    );

    parts.push(
        serde_starlark::to_string(&DownloadedNodeToolchain {
            name: "toolchain".to_string(),
            host: ":host".to_string(),
            typescript: typescript_version.map(|v| {
                format!("buckshot//node/typescript/toolchains:{v}")
            }),
            visibility: vec!["PUBLIC".to_string()],
        })
        .expect("DownloadedNodeToolchain always serializes"),
    );

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

// ==========================================================================
// TypeScript native packages (`node typescript`)
// ==========================================================================

pub struct TypescriptRenderInput<'a> {
    pub version: &'a str,
    pub host_triples: &'a [String],
    pub components: &'a [Component],
}

/// Renders one TypeScript release: an `http_archive` per host of that
/// host's `@typescript/typescript-<platform>` native package (a
/// self-contained `lib/tsc` + `lib/*.d.ts`), plus the
/// `node_host_bundle` (`:typescript-host`) node toolchain instances
/// reference. No `downloaded_node_toolchain` call of its own -- the
/// node instance owns the toolchain, this file only supplies an attr.
pub fn render_typescript(input: TypescriptRenderInput) -> anyhow::Result<String> {
    let TypescriptRenderInput {
        version,
        host_triples,
        components,
    } = input;

    if host_triples.is_empty() {
        anyhow::bail!("at least one host triple is required");
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `node typescript` command -- do not edit by hand.\n# Release: https://registry.npmjs.org/@typescript/typescript-darwin-arm64/-/typescript-darwin-arm64-{version}.tgz (plus the matching per-host native package)\n\n"
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"http_archive\")\n");
    out.push_str(
        "load(\"@buckshot//node/toolchain:node_toolchain.bzl\", \"node_host_bundle\")\n\n",
    );

    let mut parts: Vec<String> = Vec::new();

    for comp in components {
        parts.push(http_archive_for(comp));
    }

    let (archive_map, path_style_map) = host_bundle_maps(host_triples, components)?;

    parts.push(
        serde_starlark::to_string(&NodeHostBundle {
            name: "typescript-host".to_string(),
            archive: Select(archive_map),
            path_style: Select(path_style_map),
            visibility: vec!["PUBLIC".to_string()],
        })
        .expect("NodeHostBundle always serializes"),
    );

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

#[derive(Serialize)]
#[serde(rename = "alias")]
struct Alias {
    name: String,
    actual: String,
    visibility: Vec<String>,
}

/// `(major, minor, patch)` version key for an `X.Y.Z` release identifier.
fn typescript_version_key(name: &str) -> Option<(u64, u64, u64)> {
    crate::releases::semver_key(name)
}

/// Renders the rolling-alias BUCK file for the given TypeScript releases:
/// one `<major>` alias per major line, each pointing at the latest
/// release's `:typescript-host` bundle on that line.
pub fn render_typescript_aliases(releases: &[String]) -> String {
    let mut by_major: BTreeMap<u64, Vec<&String>> = BTreeMap::new();
    for release in releases {
        if let Some((major, _, _)) = typescript_version_key(release) {
            by_major.entry(major).or_default().push(release);
        }
    }
    for patches in by_major.values_mut() {
        patches.sort_by_key(|v| typescript_version_key(v));
    }

    let mut sorted: Vec<&String> = releases.iter().collect();
    sorted.sort_by_key(|v| typescript_version_key(v));

    let mut out = String::new();
    out.push_str("# @generated by buckshot's `node typescript` command -- do not edit by hand.\n");
    out.push_str(&format!(
        "# Releases: {}\n\n",
        sorted
            .iter()
            .map(|v| v.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"alias\")\n\n");

    let mut parts: Vec<String> = Vec::new();
    for (major, patches) in &by_major {
        let latest = patches.last().expect("non-empty patch list");
        parts.push(
            serde_starlark::to_string(&Alias {
                name: format!("{major}"),
                actual: format!(
                    "buckshot//node/typescript/toolchains/{latest}:typescript-host"
                ),
                visibility: vec!["PUBLIC".to_string()],
            })
            .expect("Alias always serializes"),
        );
    }

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Re-renders `dir/BUCK` (the rolling `<major>` aliases) from the
/// TypeScript releases on disk.
pub fn refresh_typescript_aliases(dir: &std::path::Path) -> anyhow::Result<()> {
    let releases = crate::releases::scan_releases(dir)?;
    for release in &releases {
        if typescript_version_key(release).is_none() {
            anyhow::bail!("{}/{release} is not an X.Y.Z release", dir.display());
        }
    }
    if releases.is_empty() {
        eprintln!(
            "node typescript: no releases under {}, leaving {}/BUCK unchanged",
            dir.display(),
            dir.display()
        );
        return Ok(());
    }
    let rendered = render_typescript_aliases(&releases);
    std::fs::write(dir.join("BUCK"), rendered)
        .with_context(|| format!("writing {}/BUCK", dir.display()))?;
    eprintln!(
        "node typescript: refreshed {}/BUCK ({})",
        dir.display(),
        releases.join(", ")
    );
    Ok(())
}

// ==========================================================================
// Rolling aliases (`node/toolchains/BUCK`)
// ==========================================================================

#[derive(Serialize)]
#[serde(rename = "toolchain_alias")]
struct ToolchainAlias {
    name: String,
    actual: String,
    visibility: Vec<String>,
}

/// `(major, minor, patch)` version key for a `vX.Y.Z` release identifier.
fn version_key(name: &str) -> Option<(u64, u64, u64)> {
    crate::releases::semver_key(name.strip_prefix('v')?)
}

/// Renders the rolling-alias BUCK file for the given releases: one
/// `v<major>` alias per major line, each pointing at the latest release on
/// that line. Deterministic: same release set, same bytes.
pub fn render_aliases(releases: &[String]) -> String {
    let mut by_major: BTreeMap<u64, Vec<&String>> = BTreeMap::new();
    for release in releases {
        if let Some((major, _, _)) = version_key(release) {
            by_major.entry(major).or_default().push(release);
        }
    }
    for patches in by_major.values_mut() {
        patches.sort_by_key(|v| version_key(v));
    }

    let mut sorted: Vec<&String> = releases.iter().collect();
    sorted.sort_by_key(|v| version_key(v));

    let mut out = String::new();
    out.push_str("# @generated by buckshot's `node toolchain` command -- do not edit by hand.\n");
    out.push_str(&format!(
        "# Releases: {}\n\n",
        sorted
            .iter()
            .map(|v| v.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"toolchain_alias\")\n\n");

    let mut parts: Vec<String> = Vec::new();
    for (major, patches) in &by_major {
        let latest = patches.last().expect("non-empty patch list");
        parts.push(
            serde_starlark::to_string(&ToolchainAlias {
                name: format!("v{major}"),
                actual: format!("buckshot//node/toolchains/{latest}:toolchain"),
                visibility: vec!["PUBLIC".to_string()],
            })
            .expect("ToolchainAlias always serializes"),
        );
    }

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Re-renders `dir/BUCK` (the rolling `v<major>` aliases) from the versioned
/// releases on disk. Leaves the file untouched when no releases exist (e.g.
/// generating to a scratch `--output` outside the repo tree).
pub fn refresh_aliases(dir: &std::path::Path) -> anyhow::Result<()> {
    let releases = crate::releases::scan_releases(dir)?;
    for release in &releases {
        if version_key(release).is_none() {
            anyhow::bail!("{}/{release} is not a vX.Y.Z release", dir.display());
        }
    }
    if releases.is_empty() {
        eprintln!(
            "node toolchain: no releases under {}, leaving {}/BUCK unchanged",
            dir.display(),
            dir.display()
        );
        return Ok(());
    }
    let rendered = render_aliases(&releases);
    std::fs::write(dir.join("BUCK"), rendered)
        .with_context(|| format!("writing {}/BUCK", dir.display()))?;
    eprintln!(
        "node toolchain: refreshed {}/BUCK ({})",
        dir.display(),
        releases.join(", "),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn major_aliases_track_latest_release() {
        let out = render_aliases(&[
            "v24.11.0".to_string(),
            "v26.4.0".to_string(),
            "v26.5.0".to_string(),
        ]);
        assert!(out.contains("name = \"v24\""));
        assert!(out.contains("buckshot//node/toolchains/v24.11.0:toolchain"));
        assert!(out.contains("name = \"v26\""));
        assert!(out.contains("buckshot//node/toolchains/v26.5.0:toolchain"));
        assert!(!out.contains("v26.4.0:toolchain"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn typescript_aliases_track_latest_patch() {
        let out = render_typescript_aliases(&["7.0.1".to_string(), "7.0.2".to_string()]);
        assert!(out.contains("name = \"7\""));
        assert!(out.contains(
            "buckshot//node/typescript/toolchains/7.0.2:typescript-host"
        ));
        assert!(!out.contains("7.0.1:typescript-host"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn typescript_attr_is_opt_in() {
        let mk = |ts: Option<&str>| {
            serde_starlark::to_string(&DownloadedNodeToolchain {
                name: "toolchain".to_string(),
                host: ":host".to_string(),
                typescript: ts.map(|v| format!("buckshot//node/typescript/toolchains:{v}")),
                visibility: vec!["PUBLIC".to_string()],
            })
            .unwrap()
        };
        let out = mk(None);
        assert!(!out.contains("typescript"));
        let out = mk(Some("7"));
        assert!(out.contains("typescript = \"buckshot//node/typescript/toolchains:7\""));
    }
}
