use std::collections::BTreeMap;

use serde::Serialize;

use super::lockfile::OptionalDep;
use super::lockfile::ResolvedPackage;

const DEFAULT_KEY: &str = "DEFAULT";

#[derive(Serialize)]
#[serde(rename = "select")]
struct Select<T>(BTreeMap<String, T>);

/// One `deps` list entry: either an unconditional target, or a flat
/// `select()` (keyed by `OptionalDep::platform`, see
/// `third-party/npm/platform/BUCK`) that resolves to the target on a
/// matching platform and `None` (dropping the entry entirely) everywhere
/// else. See `optional_dep_item`.
#[derive(Serialize)]
#[serde(untagged)]
enum DepsItem {
    Plain(String),
    Select(Select<Option<String>>),
}

/// Builds the `deps` entry for a package's own direct `optionalDependencies`
/// edge, gated on the dependency's own platform constraint (`None`
/// entirely unconditional -- shouldn't really happen for an `optional`
/// edge in practice, but falls back to an unconditional dep rather than
/// silently dropping it).
fn optional_dep_item(dep: &OptionalDep) -> DepsItem {
    let target = format!(":{}", dep.target);
    match &dep.platform {
        Some(platform) => DepsItem::Select(Select(BTreeMap::from([
            (platform.clone(), Some(target)),
            (DEFAULT_KEY.to_owned(), None),
        ]))),
        None => DepsItem::Plain(target),
    }
}

#[derive(Serialize)]
#[serde(rename = "npm_archive")]
struct NpmArchive {
    name: String,
    url: String,
    sha256: String,
    size_bytes: u64,
    // Omitted (rather than repeating `name`) whenever it matches -- true
    // for every plain, unscoped, unnested package -- since the macro
    // already defaults `package_name` to `name`.
    #[serde(skip_serializing_if = "Option::is_none")]
    package_name: Option<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    bin: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    target_compatible_with: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    deps: Vec<DepsItem>,
}

pub fn render_buck_file(pkgs: &[ResolvedPackage], lockfile_path: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `node npm buckify` command from {lockfile_path}.\n"
    ));
    out.push_str(
        "# Do not edit by hand -- run `buck2 run //buckshot -- node npm buckify` to regenerate.\n\n",
    );
    out.push_str("load(\":defs.bzl\", \"npm_archive\")\n\n");

    let parts: Vec<String> = pkgs
        .iter()
        .map(|pkg| {
            let package_name = if pkg.package_name == pkg.target_name {
                None
            } else {
                Some(pkg.package_name.clone())
            };
            let deps = pkg
                .deps
                .iter()
                .map(|target| DepsItem::Plain(format!(":{target}")))
                .chain(pkg.optional_deps.iter().map(optional_dep_item))
                .collect();
            serde_starlark::to_string(&NpmArchive {
                name: pkg.target_name.clone(),
                url: pkg.url.clone(),
                sha256: pkg.sha256.clone(),
                size_bytes: pkg.size_bytes,
                package_name,
                bin: pkg.bin.clone(),
                target_compatible_with: pkg.compatible_with.clone(),
                deps,
            })
            .expect("NpmArchive always serializes")
        })
        .collect();
    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}
