load("@buckshot//python:python_binary.bzl", "python_binary")
load("@buckshot//python:python_test.bzl", "python_test")

python_binary(
    name = "hello",
    main_function = "python.hello.main",
    srcs = ["hello.py"],
)

python_test(
    name = "hello-test",
    srcs = ["hello.py"],
)
