load("@prelude//rust:rules.bzl", "rust_binary")
load("@toolchains//:rust_dist.bzl", "downloaded_rust_toolchain")

rust_binary(
    name = "hello",
    srcs = ["main.rs"],
    toolchain = "@toolchains//:rust",
    visibility = ["PUBLIC"],
)
