use std::collections::BTreeMap;

use anyhow::Context;
use serde::Serialize;

use super::manifest;
use super::manifest::Component;

#[derive(Serialize)]
#[serde(rename = "http_archive")]
struct HttpArchive {
    name: String,
    urls: Vec<String>,
    sha256: String,
    size_bytes: u64,
    strip_prefix: String,
    #[serde(rename = "type")]
    kind: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "select")]
struct Select<T>(BTreeMap<String, T>);

#[derive(Serialize)]
#[serde(rename = "astral_python")]
struct AstralPython {
    name: String,
    archive: Select<String>,
    visibility: Vec<String>,
}

fn http_archive_for(comp: &Component) -> String {
    serde_starlark::to_string(&HttpArchive {
        name: comp.target_name.clone(),
        urls: vec![comp.url.clone()],
        sha256: comp.sha256.clone(),
        size_bytes: comp.size_bytes,
        // install_only tarballs always unpack to a single top-level `python/`.
        strip_prefix: "python".to_string(),
        kind: "tar.gz".to_string(),
        visibility: vec![],
    })
    .expect("HttpArchive always serializes")
}

pub struct RenderInput<'a> {
    pub tag: &'a str,
    pub full_version: &'a str,
    pub host_triples: &'a [String],
    pub components: &'a [Component],
}

pub fn render(input: RenderInput) -> anyhow::Result<String> {
    let RenderInput {
        tag,
        full_version,
        host_triples,
        components,
    } = input;

    if host_triples.is_empty() {
        anyhow::bail!("at least one host triple is required");
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `python toolchain` command -- do not edit by hand.\n# Release: https://github.com/astral-sh/python-build-standalone/releases/tag/{tag} (cpython {full_version})\n\n"
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"http_archive\")\n");
    out.push_str("load(\"@buckshot//python/toolchain:astral_python.bzl\", \"astral_python\")\n\n");

    let mut parts: Vec<String> = Vec::new();

    for comp in components {
        parts.push(http_archive_for(comp));
    }

    let mut archive_map = BTreeMap::new();
    for (triple, comp) in host_triples.iter().zip(components) {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        let label = format!(
            "buckshot//platforms/configs:{}",
            manifest::platform_label(cpu, os_name)
        );
        archive_map.insert(label, format!(":{}", comp.target_name));
    }

    parts.push(
        serde_starlark::to_string(&AstralPython {
            name: "python".to_string(),
            archive: Select(archive_map),
            visibility: vec!["PUBLIC".to_string()],
        })
        .expect("AstralPython always serializes"),
    );

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

// ==========================================================================
// Rolling aliases (`python/toolchains/BUCK`)
// ==========================================================================

#[derive(Serialize)]
#[serde(rename = "toolchain_alias")]
struct ToolchainAlias {
    name: String,
    actual: String,
    visibility: Vec<String>,
}

/// `(major, minor, patch)` version key. The patch component compares by its
/// leading digits so prerelease identifiers (e.g. `3.14.0rc1`) still order
/// below their final release.
fn version_key(name: &str) -> Option<(u64, u64, u64)> {
    let mut parts = name.split('.');
    let major: u64 = parts.next()?.parse().ok()?;
    let minor: u64 = parts.next()?.parse().ok()?;
    let patch_part = parts.next()?;
    if parts.next().is_some() {
        return None;
    }
    let digits: String = patch_part
        .chars()
        .take_while(|c| c.is_ascii_digit())
        .collect();
    let patch: u64 = digits.parse().ok()?;
    Some((major, minor, patch))
}

/// Whether `name` is an exact `X.Y.Z` release (no prerelease suffix):
/// preferred over suffixed siblings when the numeric keys tie.
fn is_exact_release(name: &str) -> bool {
    crate::releases::semver_key(name).is_some()
}

/// Renders the rolling-alias BUCK file for the given releases: one
/// `<major>.<minor>` alias per minor line, each pointing at the latest
/// patch release on that line. Deterministic: same release set, same bytes.
pub fn render_aliases(releases: &[String]) -> String {
    let mut by_minor: BTreeMap<(u64, u64), Vec<&String>> = BTreeMap::new();
    for release in releases {
        if let Some((major, minor, _)) = version_key(release) {
            by_minor.entry((major, minor)).or_default().push(release);
        }
    }
    // Latest patch per minor: highest patch wins; exact releases beat
    // suffixed siblings on ties; full-string comparison keeps it total.
    for patches in by_minor.values_mut() {
        patches.sort_by(|a, b| {
            version_key(a)
                .cmp(&version_key(b))
                .then_with(|| is_exact_release(a).cmp(&is_exact_release(b)))
                .then_with(|| a.cmp(b))
        });
    }

    let mut sorted: Vec<&String> = releases.iter().collect();
    sorted.sort_by(|a, b| {
        version_key(a)
            .cmp(&version_key(b))
            .then_with(|| is_exact_release(a).cmp(&is_exact_release(b)))
            .then_with(|| a.cmp(b))
    });

    let mut out = String::new();
    out.push_str("# @generated by buckshot's `python toolchain` command -- do not edit by hand.\n");
    out.push_str(&format!(
        "# Releases: {}\n\n",
        sorted
            .iter()
            .map(|v| v.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"toolchain_alias\")\n\n");

    let mut parts: Vec<String> = Vec::new();
    for ((major, minor), patches) in &by_minor {
        let latest = patches.last().expect("non-empty patch list");
        parts.push(
            serde_starlark::to_string(&ToolchainAlias {
                name: format!("{major}.{minor}"),
                actual: format!("buckshot//python/toolchains/{latest}:python"),
                visibility: vec!["PUBLIC".to_string()],
            })
            .expect("ToolchainAlias always serializes"),
        );
    }

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Re-renders `dir/BUCK` (the rolling `<major>.<minor>` aliases) from the
/// versioned releases on disk. Leaves the file untouched when no releases
/// exist (e.g. generating to a scratch `--output` outside the repo tree).
pub fn refresh_aliases(dir: &std::path::Path) -> anyhow::Result<()> {
    let releases = crate::releases::scan_releases(dir)?;
    for release in &releases {
        if version_key(release).is_none() {
            anyhow::bail!("{}/{release} is not an X.Y.Z release", dir.display());
        }
    }
    if releases.is_empty() {
        eprintln!(
            "python toolchain: no releases under {}, leaving {}/BUCK unchanged",
            dir.display(),
            dir.display()
        );
        return Ok(());
    }
    let rendered = render_aliases(&releases);
    std::fs::write(dir.join("BUCK"), rendered)
        .with_context(|| format!("writing {}/BUCK", dir.display()))?;
    eprintln!(
        "python toolchain: refreshed {}/BUCK ({})",
        dir.display(),
        releases.join(", "),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn minor_aliases_track_latest_patch() {
        let out = render_aliases(&[
            "3.13.9".to_string(),
            "3.14.5".to_string(),
            "3.14.6".to_string(),
        ]);
        assert!(out.contains("name = \"3.13\""));
        assert!(out.contains("buckshot//python/toolchains/3.13.9:python"));
        assert!(out.contains("name = \"3.14\""));
        assert!(out.contains("buckshot//python/toolchains/3.14.6:python"));
        assert!(!out.contains("3.14.5:python"));
        assert!(out.ends_with('\n'));
    }
}
