use std::collections::BTreeMap;
use std::collections::BTreeSet;

use serde::Serialize;

use super::manifest;
use super::manifest::Component;

#[derive(Serialize)]
#[serde(rename = "http_archive")]
struct HttpArchive {
    name: String,
    urls: Vec<String>,
    sha256: String,
    strip_prefix: String,
    #[serde(rename = "type")]
    kind: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "config_setting")]
struct ConfigSetting {
    name: String,
    constraint_values: Vec<String>,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "select")]
struct Select<T>(BTreeMap<String, T>);

#[derive(Serialize)]
#[serde(rename = "astral_python")]
struct AstralPython {
    name: String,
    archive: Select<String>,
    visibility: Vec<String>,
}

fn http_archive_for(comp: &Component) -> String {
    serde_starlark::to_string(&HttpArchive {
        name: comp.target_name.clone(),
        urls: vec![comp.url.clone()],
        sha256: comp.sha256.clone(),
        // install_only tarballs always unpack to a single top-level `python/`.
        strip_prefix: "python".to_string(),
        kind: "tar.gz".to_string(),
        visibility: vec![],
    })
    .expect("HttpArchive always serializes")
}

pub struct RenderInput<'a> {
    pub tag: &'a str,
    pub full_version: &'a str,
    pub host_triples: &'a [String],
    pub components: &'a [Component],
}

pub fn render(input: RenderInput) -> anyhow::Result<String> {
    let RenderInput {
        tag,
        full_version,
        host_triples,
        components,
    } = input;

    if host_triples.is_empty() {
        anyhow::bail!("at least one host triple is required");
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `python toolchain` command -- do not edit by hand.\n# Release: https://github.com/astral-sh/python-build-standalone/releases/tag/{tag} (cpython {full_version})\n\n"
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"config_setting\", \"http_archive\")\n");
    out.push_str("load(\":astral_python.bzl\", \"astral_python\")\n\n");

    let mut parts: Vec<String> = Vec::new();

    for comp in components {
        parts.push(http_archive_for(comp));
    }

    // config_setting targets -- one per unique (cpu, os) pair across hosts.
    let mut seen_platforms: BTreeSet<(String, String)> = BTreeSet::new();
    for triple in host_triples {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        seen_platforms.insert((cpu.to_string(), os_name.to_string()));
    }
    for (cpu, os_name) in &seen_platforms {
        parts.push(
            serde_starlark::to_string(&ConfigSetting {
                name: manifest::platform_label(cpu, os_name),
                constraint_values: vec![
                    format!("prelude//os/constraints:{os_name}"),
                    format!("prelude//cpu/constraints:{cpu}"),
                ],
                visibility: vec![],
            })
            .expect("ConfigSetting always serializes"),
        );
    }

    let mut archive_map = BTreeMap::new();
    for (triple, comp) in host_triples.iter().zip(components) {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        let label = format!(":{}", manifest::platform_label(cpu, os_name));
        archive_map.insert(label, format!(":{}", comp.target_name));
    }

    parts.push(
        serde_starlark::to_string(&AstralPython {
            name: "python".to_string(),
            archive: Select(archive_map),
            visibility: vec!["PUBLIC".to_string()],
        })
        .expect("AstralPython always serializes"),
    );

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}
