load("//rust:rust_binary.bzl", "rust_binary")

rust_binary(
    name="proto_codegen",
    srcs=["proto_codegen.rs"],
    deps=[
        "//third-party/rust:anyhow",
        "//third-party/rust:clap",
        "//third-party/rust:prost",
        "//third-party/rust:prost-build",
        "//third-party/rust:prost-types",
        "//third-party/rust:tempfile",
    ],
    visibility=["PUBLIC"],
)
