//! Proto codegen invoked by the `friar_protobuf_library` macro.
//!
//! Takes proto sources + a list of import roots on the CLI, runs
//! `prost-build` into a tempdir, and emits a single self-contained `lib.rs`
//! containing every package's generated code plus the `linkme`
//! schema-registration shim that registers each proto package with the
//! `//tools/proto:proto` crate's `PROTO_SCHEMAS` distributed slice.

use std::ffi::OsStr;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::Result;
use anyhow::bail;
use clap::Parser;
use tempfile::tempdir;
use prost::Message;

#[derive(Parser, Debug)]
#[command(about = "Compile .proto sources into a single lib.rs")]
struct Args {
    /// Output path for the generated `lib.rs`.
    #[arg(long)]
    out: PathBuf,

    /// Path to the `protoc` binary to use. 
    #[arg(long)]
    protoc: Option<PathBuf>,

    /// Import roots. Pass once per `-I` directory.
    #[arg(long = "proto-path")]
    proto_paths: Vec<PathBuf>,

    /// Proto sources to compile. Paths must be resolvable against one of `--proto-path`.
    protos: Vec<PathBuf>,
}

fn main() -> Result<()> {
    let args = Args::parse();

    if args.protos.is_empty() {
        bail!("no .proto files provided");
    }

    let tmp = tempdir()?;
    let descriptor_path = tmp.path().join("descriptor_set.bin");

    let mut config = prost_build::Config::new();
    if let Some(protoc) = args.protoc {
        config.protoc_executable(protoc);
    }
    config
        .out_dir(tmp.path())
        .type_attribute(".", "#[allow(dead_code)]")
        .file_descriptor_set_path(&descriptor_path)
        .enable_type_names()
        .compile_protos(&args.protos, &args.proto_paths)
        .context("prost-build compile failed")?;

    let descriptor_bytes =
        fs::read(&descriptor_path).context("reading prost-emitted descriptor set")?;
    let descriptor = prost_types::FileDescriptorSet::decode(&descriptor_bytes[..])
        .context("decoding descriptor set")?;

    let mut lib = String::new();
    writeln!(lib, "//! Generated by tools/proto_codegen — do not edit.")?;
    writeln!(lib)?;

    let mut packages: Vec<String> = Vec::new();
    for entry in fs::read_dir(tmp.path())? {
        let entry = entry?;
        let path = entry.path();
        if path.extension() == Some(OsStr::new("rs"))
            && let Some(stem) = path.file_stem().and_then(|s| s.to_str())
        {
            packages.push(stem.to_string());
        }
    }
    packages.sort();

    // Inline each prost-emitted `<package>.rs` directly at the top level of
    // the generated crate so consumers see types as `friarlog_proto::Pose2d`
    // rather than `friarlog_proto::friarlog::geometry::Pose2d`.
    for pkg in &packages {
        let pkg_path = tmp.path().join(format!("{pkg}.rs"));
        let pkg_src = fs::read_to_string(&pkg_path)
            .with_context(|| format!("reading prost output {}", pkg_path.display()))?;
        writeln!(lib, "// --- {pkg} ---")?;
        lib.push_str(&pkg_src);
        writeln!(lib)?;
    }
    
    std::fs::write(&args.out, lib.as_bytes())
        .with_context(|| format!("writing {}", args.out.display()))?;

    Ok(())
}