#!/usr/bin/env python3
"""Generate tools/buck/BUCK for a facebook/buck2 GitHub release.

Fetches the release's dotslash manifests (parsed for per-platform URLs only,
never executed) for starlark_fmt and rust-project, downloads each platform's
`.zst` once to record its sha256 (dotslash records blake3, which buck cannot
verify), and writes one `zst_binary` rule per tool with a single
`url_sha256` (url, sha256) tuple `select()`ed by platform.

Usage:
    python3 tools/buck/generate.py 2026-10-01
    python3 tools/buck/generate.py 2026-10-01 --output tools/buck/BUCK
"""

import argparse
import hashlib
import json
import urllib.error
import urllib.request
from pathlib import Path

RELEASE_BASE = "https://github.com/facebook/buck2/releases/download"
BINARIES = ("starlark_fmt", "rust-project")

# Dotslash platform -> repo config_setting, in the select() key order used by
# the repo's other toolchain BUCK files. Covers the same four platforms the
# hermetic CPython decompressor (//python/toolchain) is available for.
PLATFORMS = {
    "linux-aarch64": "linux-arm64",
    "linux-x86_64": "linux-x86_64",
    "macos-aarch64": "macos-arm64",
    "windows-x86_64": "windows-x86_64",
}
CONFIG_CELL = "buckshot//platforms/configs"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(
        url, headers={"User-Agent": "buckshot-tools-buck-generate/1.0"}
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            return resp.read()
    except urllib.error.HTTPError as e:
        raise SystemExit(f"error: {url}: HTTP {e.code} {e.reason}") from e
    except urllib.error.URLError as e:
        raise SystemExit(f"error: {url}: {e.reason}") from e


def parse_dotslash(data: bytes, binary: str, tag: str) -> dict:
    text = data.decode("utf-8")
    _shebang, _nl, body = text.partition("\n")
    try:
        return json.loads(body)
    except json.JSONDecodeError as e:
        raise SystemExit(
            f"error: release {tag} has no usable dotslash manifest for "
            f"{binary} (is {binary} published in that release?): {e}"
        ) from e


def sha256_of(url: str, expect_size: int) -> str:
    data = fetch(url)
    if len(data) != expect_size:
        raise SystemExit(
            f"error: {url}: downloaded {len(data)} bytes, manifest says {expect_size}"
        )
    return hashlib.sha256(data).hexdigest()


def collect(tag: str) -> dict[str, dict[str, tuple[str, str]]]:
    """{binary: {config: (url, sha256)}} for every binary x platform."""
    collected = {}
    for binary in BINARIES:
        manifest = parse_dotslash(fetch(f"{RELEASE_BASE}/{tag}/{binary}"), binary, tag)
        try:
            entries = manifest["platforms"]
        except KeyError as e:
            raise SystemExit(
                f"error: release {tag} manifest for {binary} has no 'platforms' object"
            ) from e
        per_config = {}
        for dotslash_platform, config in PLATFORMS.items():
            try:
                entry = entries[dotslash_platform]
            except KeyError as e:
                raise SystemExit(
                    f"error: release {tag} manifest for {binary} has no "
                    f"platform {dotslash_platform!r}"
                ) from e
            url = entry["providers"][0]["url"]
            print(f"{binary} {config}: {url}", flush=True)
            per_config[config] = (url, sha256_of(url, entry["size"]))
        collected[binary] = per_config
    return collected


def render(tag: str, collected: dict[str, dict[str, tuple[str, str]]]) -> str:
    lines = [
        f"# @generated by `python3 tools/buck/generate.py {tag}` -- do not edit by hand.",
        f"# Release: https://github.com/facebook/buck2/releases/tag/{tag}",
        "",
        'load(":zst_binary.bzl", "zst_binary")',
    ]
    for binary, per_config in collected.items():
        pairs = "".join(
            f'\n        "{CONFIG_CELL}:{config}": ("{url}", "{sha256}"),'
            for config, (url, sha256) in per_config.items()
        )
        lines += [
            "",
            "zst_binary(",
            f'    name="{binary}",',
            f"    url_sha256=select({{{pairs}",
            "    }),",
            '    visibility=["PUBLIC"],',
            ")",
        ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate tools/buck/BUCK for a facebook/buck2 release tag."
    )
    parser.add_argument("tag", help="release tag, e.g. 2026-10-01")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent / "BUCK",
        help="where to write the BUCK file (default: BUCK next to this script)",
    )
    args = parser.parse_args()

    output = args.output
    output.write_text(render(args.tag, collect(args.tag)))
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
