use std::collections::BTreeMap;

use serde::Serialize;

use super::lockfile::ResolvedPackage;

const DEFAULT_STRIP_PREFIX: &str = "package";

#[derive(Serialize)]
#[serde(rename = "npm_archive")]
struct NpmArchive {
    name: String,
    url: String,
    sha256: String,
    // Omitted (rather than repeating `name`) whenever it matches -- true
    // for every plain, unscoped, unnested package -- since the macro
    // already defaults `package_name` to `name`.
    #[serde(skip_serializing_if = "Option::is_none")]
    package_name: Option<String>,
    // Outer `None` omits the field entirely, relying on the macro's own
    // `strip_prefix = "package"` default. `Some(None)` explicitly emits
    // `strip_prefix = None` for a tarball with no top-level wrapper
    // directory at all -- distinct from omitting the field, which would
    // wrongly fall back to stripping `"package"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    strip_prefix: Option<Option<String>>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    bin: BTreeMap<String, String>,
}

pub fn render_buck_file(pkgs: &[ResolvedPackage], lockfile_path: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `npm buckify` command from {lockfile_path}.\n"
    ));
    out.push_str("# Do not edit by hand -- run `buck2 run //buckshot -- npm buckify` to regenerate.\n\n");
    out.push_str("load(\":defs.bzl\", \"npm_archive\")\n\n");

    let parts: Vec<String> = pkgs
        .iter()
        .map(|pkg| {
            let package_name = if pkg.package_name == pkg.target_name {
                None
            } else {
                Some(pkg.package_name.clone())
            };
            let strip_prefix = match &pkg.strip_prefix {
                Some(s) if s == DEFAULT_STRIP_PREFIX => None,
                other => Some(other.clone()),
            };
            serde_starlark::to_string(&NpmArchive {
                name: pkg.target_name.clone(),
                url: pkg.url.clone(),
                sha256: pkg.sha256.clone(),
                package_name,
                strip_prefix,
                bin: pkg.bin.clone(),
            })
            .expect("NpmArchive always serializes")
        })
        .collect();
    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}
