http_archive(
    name = "protoc-35.1-osx-aarch_64",
    sha256 = "193289af0470c6a1aada357d4fba0bbf8d78bfaac8b5e42ca30af2ef75583de2",
    size_bytes = 2585575,
    sub_targets = ["bin/protoc"],
    urls = ["https://github.com/protocolbuffers/protobuf/releases/download/v35.1/protoc-35.1-osx-aarch_64.zip"],
)

http_archive(
    name = "protoc-35.1-linux-x86_64",
    sha256 = "6930ebf62bd4ea607b98fff052596c6ee564b9835b4ce172c75a3f53ae9d91b7",
    size_bytes = 3633928,
    sub_targets = ["bin/protoc"],
    urls = ["https://github.com/protocolbuffers/protobuf/releases/download/v35.1/protoc-35.1-linux-x86_64.zip"],
)

http_archive(
    name = "protoc-35.1-linux-aarch_64",
    sha256 = "01bf9d08808c7f96678b63f4bd8efa559bb4f83d5a7a270d5edaf507f9d5d9cf",
    size_bytes = 3583287,
    sub_targets = ["bin/protoc"],
    urls = ["https://github.com/protocolbuffers/protobuf/releases/download/v35.1/protoc-35.1-linux-aarch_64.zip"],
)

http_archive(
    name = "protoc-35.1-win64",
    sha256 = "5d3ff218d7d91eea95f7569bcb5a98f3030f8996d44151279d9772edcff76082",
    size_bytes = 3518494,
    sub_targets = ["bin/protoc.exe"],
    urls = ["https://github.com/protocolbuffers/protobuf/releases/download/v35.1/protoc-35.1-win64.zip"],
)

alias(
    name = "protoc",
    actual = select({
        "//platforms/configs:linux-arm64": ":protoc-35.1-linux-aarch_64[bin/protoc]",
        "//platforms/configs:linux-x86_64": ":protoc-35.1-linux-x86_64[bin/protoc]",
        "//platforms/configs:macos-arm64": ":protoc-35.1-osx-aarch_64[bin/protoc]",
        "//platforms/configs:windows-x86_64": ":protoc-35.1-win64[bin/protoc.exe]",
    }),
    visibility = ["PUBLIC"],
)
