use std::collections::BTreeMap;

use serde::Serialize;

use super::manifest;
use super::manifest::Component;

#[derive(Serialize)]
#[serde(rename = "http_archive")]
struct HttpArchive {
    name: String,
    urls: Vec<String>,
    sha256: String,
    size_bytes: u64,
    strip_prefix: String,
    #[serde(rename = "type")]
    kind: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "select")]
struct Select<T>(BTreeMap<String, T>);

#[derive(Serialize)]
#[serde(rename = "python_bootstrap_binary")]
struct PythonBootstrapBinary {
    name: String,
    main: String,
}

#[derive(Serialize)]
#[serde(rename = "zig_host_bundle")]
struct ZigHostBundle {
    name: String,
    archive: Select<String>,
    os: Select<String>,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "export_file")]
struct ExportFile {
    name: String,
    src: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "macos_sdk_shim")]
struct MacosSdkShim {
    name: String,
    libiconv_tbd: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "zig_cxx_toolchain")]
struct ZigCxxToolchain {
    name: String,
    host: String,
    macos_sdk_shim: String,
    target: Select<String>,
    visibility: Vec<String>,
}

fn http_archive_for(comp: &Component) -> String {
    serde_starlark::to_string(&HttpArchive {
        name: comp.target_name.clone(),
        urls: vec![comp.url.clone()],
        sha256: comp.sha256.clone(),
        size_bytes: comp.size_bytes,
        strip_prefix: comp.strip_prefix.clone(),
        kind: comp.kind.clone(),
        visibility: vec![],
    })
    .expect("HttpArchive always serializes")
}

fn config_label(cpu: &str, os_name: &str) -> String {
    format!(
        "buckshot//platforms/configs:{}",
        manifest::platform_label(cpu, os_name)
    )
}

pub struct RenderInput<'a> {
    pub index_url: &'a str,
    pub version: &'a str,
    pub date: &'a str,
    pub host_triples: &'a [String],
    pub components: &'a [Component],
    pub target_triples: &'a [String],
}

pub fn render(input: RenderInput) -> anyhow::Result<String> {
    let RenderInput {
        index_url,
        version,
        date,
        host_triples,
        components,
        target_triples,
    } = input;

    if host_triples.is_empty() {
        anyhow::bail!("at least one host triple is required");
    }
    if target_triples.is_empty() {
        anyhow::bail!("at least one target triple is required");
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `cxx toolchain` command -- do not edit by hand.\n# Zig: {index_url} ({version}, {date})\n\n"
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"export_file\", \"http_archive\")\n");
    out.push_str(
        "load(\":zig_toolchain.bzl\", \"macos_sdk_shim\", \"zig_cxx_toolchain\", \"zig_host_bundle\")\n\n",
    );

    let mut parts: Vec<String> = Vec::new();

    parts.push(
        "\
# Response-file flattener shared by every `zig <subcommand>` the toolchain
# drives (see zig_tool_wrapper.py). Runs on the hermetic bootstrap python,
# so it works identically on mac/linux/windows hosts with no sh/bash.\n"
            .to_string()
            + &serde_starlark::to_string(&PythonBootstrapBinary {
                name: "zig_tool_wrapper".to_string(),
                main: "zig_tool_wrapper.py".to_string(),
            })
            .expect("PythonBootstrapBinary always serializes"),
    );

    for comp in components {
        parts.push(http_archive_for(comp));
    }

    let mut archive_map = BTreeMap::new();
    let mut os_map = BTreeMap::new();
    for (triple, comp) in host_triples.iter().zip(components) {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        let label = config_label(cpu, os_name);
        archive_map.insert(label.clone(), format!(":{}", comp.target_name));
        os_map.insert(label, os_name.to_string());
    }

    parts.push(
        "\
# The rust toolchain's `zig_host` exec_dep reads the host Zig binary
# from this bundle for its windows-gnu dlltool shims.\n"
            .to_string()
            + &serde_starlark::to_string(&ZigHostBundle {
                name: "host".to_string(),
                archive: Select(archive_map),
                os: Select(os_map),
                visibility: vec!["buckshot//rust/toolchain:".to_string()],
            })
            .expect("ZigHostBundle always serializes"),
    );

    parts.push(
        serde_starlark::to_string(&ExportFile {
            name: "libiconv.tbd".to_string(),
            src: "macos/libiconv.tbd".to_string(),
            visibility: vec![],
        })
        .expect("ExportFile always serializes"),
    );

    parts.push(
        serde_starlark::to_string(&MacosSdkShim {
            name: "macos_sdk_shim".to_string(),
            libiconv_tbd: ":libiconv.tbd".to_string(),
            visibility: vec![],
        })
        .expect("MacosSdkShim always serializes"),
    );

    // Target select: config label -> `zig -target` triple. Env-insensitive
    // (both windows envs map to `x86_64-windows-gnu`), so collisions
    // overwrite with the identical value.
    let mut target_map = BTreeMap::new();
    for triple in target_triples {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        target_map.insert(
            config_label(cpu, os_name),
            manifest::zig_target_for(cpu, os_name)?.to_string(),
        );
    }

    parts.push(
        serde_starlark::to_string(&ZigCxxToolchain {
            name: "toolchain".to_string(),
            host: ":host".to_string(),
            macos_sdk_shim: ":macos_sdk_shim".to_string(),
            target: Select(target_map),
            visibility: vec!["PUBLIC".to_string()],
        })
        .expect("ZigCxxToolchain always serializes"),
    );

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}
