use std::collections::BTreeMap;

use anyhow::Context;
use serde::Serialize;

use super::manifest;
use super::manifest::Component;

#[derive(Serialize)]
#[serde(rename = "http_archive")]
struct HttpArchive {
    name: String,
    urls: Vec<String>,
    sha256: String,
    size_bytes: u64,
    strip_prefix: String,
    #[serde(rename = "type")]
    kind: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "select")]
struct Select<T>(BTreeMap<String, T>);

#[derive(Serialize)]
#[serde(rename = "zig_host_bundle")]
struct ZigHostBundle {
    name: String,
    archive: Select<String>,
    os: Select<String>,
    visibility: Vec<String>,
}

/// `c/cxx_compiler_flags` for the toolchain: `-O3 -DNDEBUG` on
/// `buckshot//mode:mode[release]`, the toolchain default (zig's own
/// no-args default = `-O0`, no `-g`) everywhere else.
fn mode_compiler_flags() -> Select<Vec<String>> {
    Select(BTreeMap::from([
        (
            "buckshot//mode:mode[release]".to_string(),
            vec!["-O3".to_string(), "-DNDEBUG".to_string()],
        ),
        ("DEFAULT".to_string(), Vec::new()),
    ]))
}

#[derive(Serialize)]
#[serde(rename = "zig_cxx_toolchain")]
struct ZigCxxToolchain {
    name: String,
    host: String,
    macos_sdk_shim: String,
    target: Select<String>,
    c_compiler_flags: Select<Vec<String>>,
    cxx_compiler_flags: Select<Vec<String>>,
    visibility: Vec<String>,
}

fn http_archive_for(comp: &Component) -> String {
    serde_starlark::to_string(&HttpArchive {
        name: comp.target_name.clone(),
        urls: vec![comp.url.clone()],
        sha256: comp.sha256.clone(),
        size_bytes: comp.size_bytes,
        strip_prefix: comp.strip_prefix.clone(),
        kind: comp.kind.clone(),
        visibility: vec![],
    })
    .expect("HttpArchive always serializes")
}

fn config_label(cpu: &str, os_name: Option<&str>) -> String {
    format!(
        "buckshot//platforms/configs:{}",
        manifest::platform_label(cpu, os_name)
    )
}

pub struct RenderInput<'a> {
    pub index_url: &'a str,
    pub version: &'a str,
    pub date: &'a str,
    pub host_triples: &'a [String],
    pub components: &'a [Component],
    pub target_triples: &'a [String],
}

pub fn render(input: RenderInput) -> anyhow::Result<String> {
    let RenderInput {
        index_url,
        version,
        date,
        host_triples,
        components,
        target_triples,
    } = input;

    if host_triples.is_empty() {
        anyhow::bail!("at least one host triple is required");
    }
    if target_triples.is_empty() {
        anyhow::bail!("at least one target triple is required");
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# @generated by buckshot's `cxx toolchain` command -- do not edit by hand.\n# Zig: {index_url} ({version}, {date})\n\n"
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"http_archive\")\n");
    out.push_str(
        "load(\"@buckshot//cxx/toolchain:zig_toolchain.bzl\", \"zig_cxx_toolchain\", \"zig_host_bundle\")\n\n",
    );

    // The `:zig_tool_wrapper` `python_bootstrap_binary` and the macOS SDK
    // shim live in the static cxx/toolchain/BUCK, shared by every release
    // -- this file holds only this release's archives.
    let mut parts: Vec<String> = Vec::new();

    for comp in components {
        parts.push(http_archive_for(comp));
    }

    let mut archive_map = BTreeMap::new();
    let mut os_map = BTreeMap::new();
    for (triple, comp) in host_triples.iter().zip(components) {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        let label = config_label(cpu, os_name);
        archive_map.insert(label.clone(), format!(":{}", comp.target_name));
        let os_name = os_name
            .ok_or_else(|| anyhow::anyhow!("host triple {triple:?} has no OS"))?;
        os_map.insert(label, os_name.to_string());
    }

    parts.push(
        "\
# The rust toolchain's `zig_host` exec_dep reads the host Zig binary
# from this bundle (via the `buckshot//cxx/toolchains:host` alias) for
# its windows-gnu dlltool shims.\n"
            .to_string()
            + &serde_starlark::to_string(&ZigHostBundle {
                name: "host".to_string(),
                archive: Select(archive_map),
                os: Select(os_map),
                visibility: vec!["buckshot//cxx/toolchains:".to_string()],
            })
            .expect("ZigHostBundle always serializes"),
    );

    // Target select: config label -> `zig -target` triple. Env-insensitive
    // (both windows envs map to `x86_64-windows-gnu`), so collisions
    // overwrite with the identical value.
    let mut target_map = BTreeMap::new();
    for triple in target_triples {
        let (cpu, os_name) = manifest::platform_for(triple)?;
        target_map.insert(
            config_label(cpu, os_name),
            manifest::zig_target_for(cpu, os_name)?.to_string(),
        );
    }

    parts.push(
        serde_starlark::to_string(&ZigCxxToolchain {
            name: "toolchain".to_string(),
            host: ":host".to_string(),
            macos_sdk_shim: "buckshot//cxx/toolchain:macos_sdk_shim".to_string(),
            target: Select(target_map),
            c_compiler_flags: mode_compiler_flags(),
            cxx_compiler_flags: mode_compiler_flags(),
            visibility: vec!["PUBLIC".to_string()],
        })
        .expect("ZigCxxToolchain always serializes"),
    );

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

// ==========================================================================
// Rolling aliases (`cxx/toolchains/BUCK`)
// ==========================================================================

#[derive(Serialize)]
#[serde(rename = "toolchain_alias")]
struct ToolchainAlias {
    name: String,
    actual: String,
    visibility: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename = "alias")]
struct Alias {
    name: String,
    actual: String,
    visibility: Vec<String>,
}

/// Renders the rolling-alias BUCK file for the given releases: one
/// `<major>.<minor>` alias per minor line, each pointing at the latest
/// patch release on that line, plus the `host` alias (the rust toolchain's
/// `zig_host` bundle) tracking the latest release overall. Deterministic:
/// same release set, same bytes.
pub fn render_aliases(releases: &[String]) -> String {
    let mut by_minor: BTreeMap<(u64, u64), Vec<&String>> = BTreeMap::new();
    for release in releases {
        if let Some((major, minor, _)) = crate::releases::semver_key(release) {
            by_minor.entry((major, minor)).or_default().push(release);
        }
    }
    for patches in by_minor.values_mut() {
        patches.sort_by_key(|v| crate::releases::semver_key(v));
    }

    let mut sorted: Vec<&String> = releases.iter().collect();
    sorted.sort_by_key(|v| crate::releases::semver_key(v));

    let mut out = String::new();
    out.push_str("# @generated by buckshot's `cxx toolchain` command -- do not edit by hand.\n");
    out.push_str(&format!(
        "# Releases: {}\n\n",
        sorted
            .iter()
            .map(|v| v.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str("load(\"@prelude//:rules.bzl\", \"toolchain_alias\")\n\n");

    let mut parts: Vec<String> = Vec::new();
    for ((major, minor), patches) in &by_minor {
        let latest = patches.last().expect("non-empty patch list");
        parts.push(
            serde_starlark::to_string(&ToolchainAlias {
                name: format!("{major}.{minor}"),
                actual: format!("buckshot//cxx/toolchains/{latest}:toolchain"),
                visibility: vec!["PUBLIC".to_string()],
            })
            .expect("ToolchainAlias always serializes"),
        );
    }
    if let Some(latest) = sorted.last() {
        parts.push(
            "# Rolling host-Zig bundle for the rust toolchain's `zig_host` exec_dep\n# (windows-gnu dlltool shims), tracking the latest release overall.\n"
                .to_string()
                + &serde_starlark::to_string(&Alias {
                    name: "host".to_string(),
                    actual: format!("buckshot//cxx/toolchains/{latest}:host"),
                    visibility: vec!["PUBLIC".to_string()],
                })
                .expect("Alias always serializes"),
        );
    }

    out.push_str(&parts.join("\n"));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Re-renders `dir/BUCK` (the rolling `<major>.<minor>` + `host` aliases)
/// from the versioned releases on disk. Leaves the file untouched when no
/// releases exist (e.g. generating to a scratch `--output` outside the repo
/// tree).
pub fn refresh_aliases(dir: &std::path::Path) -> anyhow::Result<()> {
    let releases = crate::releases::scan_releases(dir)?;
    for release in &releases {
        if crate::releases::semver_key(release).is_none() {
            anyhow::bail!("{}/{release} is not an X.Y.Z release", dir.display());
        }
    }
    if releases.is_empty() {
        eprintln!(
            "cxx toolchain: no releases under {}, leaving {}/BUCK unchanged",
            dir.display(),
            dir.display()
        );
        return Ok(());
    }
    let rendered = render_aliases(&releases);
    std::fs::write(dir.join("BUCK"), rendered)
        .with_context(|| format!("writing {}/BUCK", dir.display()))?;
    eprintln!(
        "cxx toolchain: refreshed {}/BUCK ({})",
        dir.display(),
        releases.join(", "),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn minor_and_host_aliases_track_latest() {
        let out = render_aliases(&["0.15.1".to_string(), "0.16.0".to_string()]);
        assert!(out.contains("name = \"0.15\""));
        assert!(out.contains("buckshot//cxx/toolchains/0.15.1:toolchain"));
        assert!(out.contains("name = \"0.16\""));
        assert!(out.contains("buckshot//cxx/toolchains/0.16.0:toolchain"));
        assert!(out.contains("name = \"host\""));
        assert!(out.contains("buckshot//cxx/toolchains/0.16.0:host"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn mode_flags_select_release_opt() {
        #[derive(Serialize)]
        #[serde(rename = "zig_cxx_toolchain")]
        struct Probe {
            cxx_compiler_flags: Select<Vec<String>>,
        }
        let out = serde_starlark::to_string(&Probe {
            cxx_compiler_flags: mode_compiler_flags(),
        })
        .unwrap();
        assert!(out.contains("\"buckshot//mode:mode[release]\""));
        assert!(out.contains("\"-O3\""));
        assert!(out.contains("\"-DNDEBUG\""));
        assert!(out.contains("\"DEFAULT\""));
    }
}
