name: Buck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: facebook/install-dotslash@latest
    - name: buck2 test tests//...
      run: ./buck2 test tests//...
